<a href="https://colab.research.google.com/github/Akshatasthana18/Akshat/blob/main/modelselect_AIC_and_BIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

In [15]:
cow=pd.read_csv('/content/DataScience_salaries_2024.csv')

In [16]:
cow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14838 entries, 0 to 14837
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           14838 non-null  int64
 1   experience_level    14838 non-null  object
 2   employment_type     14838 non-null  object
 3   job_title           14838 non-null  object
 4   salary              14838 non-null  int64
 5   salary_currency     14838 non-null  object
 6   salary_in_usd       14838 non-null  int64
 7   employee_residence  14838 non-null  object
 8   remote_ratio        14838 non-null  int64
 9   company_location    14838 non-null  object
 10  company_size        14838 non-null  object
dtypes: int64(4), object(7)
memory usage: 1.2+ MB

In [17]:
cow.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L
1,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L
2,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L
3,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S
4,2022,SE,FT,Lead Machine Learning Engineer,7500000,INR,95386,IN,50,IN,L

In [18]:
cow.tail()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
14833,2022,MI,FT,Business Intelligence Developer,15000,USD,15000,GH,100,GH,M
14834,2020,EX,FT,Staff Data Analyst,15000,USD,15000,NG,0,CA,M
14835,2021,EN,FT,Machine Learning Developer,15000,USD,15000,TH,100,TH,L
14836,2022,EN,FT,Data Analyst,15000,USD,15000,ID,0,ID,L
14837,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S

In [19]:
cow.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  14838.000000  1.483800e+04   14838.000000  14838.000000
mean    2023.138900  1.650227e+05  149874.718763     32.760480
std        0.700799  3.562354e+05   69009.181349     46.488278
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2023.000000  1.021000e+05  102000.000000      0.000000
50%     2023.000000  1.422000e+05  141300.000000      0.000000
75%     2024.000000  1.875000e+05  185900.000000    100.000000
max     2024.000000  3.040000e+07  800000.000000    100.000000

In [20]:
cow.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [21]:
cow.shape

(14838, 11)

In [30]:
x=cow[['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size']]

In [31]:
y=cow[['salary_in_usd']]

In [32]:
y.shape

(14838, 1)

In [33]:
x.shape

(14838, 10)

In [34]:
np.random.seed(0)
X = np.random.rand(100, 3)
y = 2.5 + 1.2 * X[:, 0] + 0.8 * X[:, 1] - 1.5 * X[:, 2] + np.random.normal(0, 0.2, 100)

In [35]:
X = sm.add_constant(X)

In [36]:
models = {
    'model_1': sm.OLS(y, X[:, :2]).fit(),
    'model_2': sm.OLS(y, X[:, :3]).fit(),
    'model_3': sm.OLS(y, X).fit()
}

In [37]:
results = []
for name, model in models.items():
    aic = model.aic
    bic = model.bic
    results.append((name, aic, bic))

In [38]:
results_df = pd.DataFrame(results, columns=['Model', 'AIC', 'BIC'])
print(results_df)

     Model         AIC         BIC
0  model_1  155.727272  160.937613
1  model_2  126.017800  133.833311
2  model_3  -44.607605  -34.186924